on: push
name: CI
jobs:
  detect-diff:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete file
        run: yarn remove-file
      - name: git add -N
        run: git add -N .
      - name: git diff
        run: git diff --exit-code
