on: push
name: CI
jobs:
  check-create:
    name: detect-create
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create file
        run: yarn create-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code
  check-update:
    name: detect-update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update file
        run: yarn update-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code
  check-remove:
    name: detect-remove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete file
        run: yarn remove-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code
