on: push
name: CI
jobs:
  detect-diff:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add file
        run: yarn create-file
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Your commit message"
          add: "src/main.js"
      - name: git-diff
        run: echo git diff
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            src/**/*.js
      - name: echo
        run: echo '${{ env.GIT_DIFF }}'
      - name: Install Package dependencies
        run: yarn install
        if: env.GIT_DIFF
      - name: Check code style
        # Check only if there are differences in the source code
        run: yarn lint
        if: env.GIT_DIFF
