on: pull_request
name: CI
permissions:
  contents: read
jobs:
  check-create:
    name: detect-diff
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create file
        run: yarn create-file
      - name: git add
        run: git add .
      - name: git diff
        id: diff
        run: git diff --cached --exit-code
        continue-on-error: true
      - name: tsc
        run: yarn tsc .github/workflows/checkDiff.ts --outDir .github/workflows --lib es2019
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/workflows/checkDiff.js')
            await script(github, context, ${{ steps.diff.outcome == 'success' }})
      - name: Status
        if: ${{ steps.diff.outcome == 'failure' }}
        run: exit 1

  check-update:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update file
        run: yarn update-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code

  check-remove:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete file
        run: yarn remove-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code
