on: push
name: CI
jobs:
  detect-diff:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: add file
        run: yarn create-file
      - name: git-diff
        run: git diff --name-only | cat
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            src/**/*.js
      - name: echo
        run: echo '${{ env.GIT_DIFF }}'
      - name: Install Package dependencies
        run: yarn install
        if: env.GIT_DIFF
      - name: Check code style
        run: yarn lint
        if: env.GIT_DIFF
