on: pull_request
name: CI
jobs:
  check-create:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create file
        run: yarn create-file
      - name: git add
        run: git add .
      - name: git diff
        id: diff
        run: git diff --cached --exit-code
        continue-on-error: true
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/checkDiff.js')
            script({ github, context, isSuccess: ${{ steps.diff.outcome == 'success' }} })
      - name: Status
        if: ${{ steps.diff.outcome == 'failure' }}
        run: exit 1

  check-update:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update file
        run: yarn update-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code

  check-remove:
    name: detect-diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: delete file
        run: yarn remove-file
      - name: git add
        run: git add .
      - name: git diff
        run: git diff --cached --exit-code
